{
  "name": "bookwise-frontend",
  "version": "1.0.0",
  "scripts": {
    "build": "vite build",
    "preview": "vite preview"
  },
  "buildCommand": "npm run build",
  "outputDirectory": "dist",
  "installCommand": "npm install",
  "framework": "vite"
}
